# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a0255eb3bd04ad42c90e3c5a7c94dc7052c40d32c5ac1497ef6c89d5c188b05a48372cac0c5561c84a187dd8862a3b3fc12db60a49b6a4e8917b763f4fe76c

test:
  secret_key_base: 0942c4e41d84d534c2213c02332c3b72797c8f16057eef69b81c3816d9567ef7a5386865920832e3a65c33325958d0391ef34ce1205d846858283569d1ad64d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
